### ISSUE TITLE
Installer cannot connect to the database on installer

### ISSUE THREAD

**Issue by willjackson** [badcamp/camp_distro#86]
This is due to the `settings.local.php` not being loaded, due to the bottom lines of settings.php having the the configuration commented out.

Since the changes needed are located in `settings.php` and that file is included within the `.gitignore`, the recommended path to resolve would be to include a base `settings.php` file within the docksal project that includes the uncommented lines.  This file will then be copied into the project on the `fin init` command is run.

**Comment by sean-e-dietrich** [comment]
@willjackson closing this ticket and moved it over to the installer https://github.com/badcamp/camp_distro_installer/issues/1
